### ISSUE TITLE
LiveTemplates

### ISSUE THREAD

**Issue by 2amedia** [thekalinga/bootstrap4-intellij#2]
after you reinstall the plugin are not created LiveTemplates

**Comment by prog110** [comment]
I just reinstalled the extension in Webstorm 2017.1 EAP.

I'm able to use the template in a html, typescript files without any issue.

Please check whether you are using `b4` or `bs4`. You need to use `b4` not `bs4`

If the issue still persists, please specify the flavor & version of intellij are you using

**Comment by 2amedia** [comment]
the issue still persists for me. I'm use PhpStorm 2016.3.2

**Comment by prog110** [comment]
@2amedia Now that 2017.1 is out, can you check this once again?
