### ISSUE TITLE
Navbar does not show

### ISSUE THREAD

**Issue by likeweb** [thekalinga/bootstrap4-intellij#3]
Hi, I am  using your plugin and its very great.
I found an issue in the navbar component under src/util/resources/bootstrap/components/navbar/default.html
In the nav tag there have to be added the navbar-toggleable-md class.
You have added it in the div with the class collapse -> please remove it from there and add insted off the class navbar-collapse.
After that, the b4-navbar-default should work correctly in the plugin.

Thanks.

**Comment by prog110** [comment]
Hi,

I'm a bit busy with my other work. Since the file in question is a simple html snippet, is it possible for you to modify the file & create a pull request?

Thanks

**Comment by prog110** [comment]
Published v6.0.0 with the required fixes
