### ISSUE TITLE
b4 beta ? :)

### ISSUE THREAD

**Issue by ruscon** [thekalinga/bootstrap4-intellij#4]

**Comment by prog110** [comment]
Hi,

I'm not actively working on bootstrap. So not sure how many snippets would be affected & am having very lil time work on this right now.

Would appreciate if you/someone else can submit a pull request after modifying the snippets (these are vanilla html snippets with simple placeholders) under src/util/resources/bootstrap directory.

**Comment by prog110** [comment]
Published v6.0.0 with the required fixes
