### ISSUE TITLE
Cannot use ctrl+space.

### ISSUE THREAD

**Issue by felixmaker** [thekalinga/bootstrap4-intellij#5]
I use ctrl+space but no reaction

**Comment by nyonor** [comment]
Me 2... mac os high sierra and phpstorm

**Comment by prog110** [comment]
Use `Ctrl+J` if you are using middle of the word. `Ctrl+Space` only works for cases where start typing the prefix. Thats how IntelliJ works

This is already mentioned in the README

**Comment by nyonor** [comment]
In my case the snippet shows only if i type with "<" then it shows up, then i select needed, but the first opened "<" remains and its duplicated...
