### ISSUE TITLE
Bootstrap v4 official

### ISSUE THREAD

**Issue by clarkedesign** [thekalinga/bootstrap4-intellij#7]
Hi,  Can we get the plugin updated please to use the new live version rather than alpha 6

**Comment by wyatt-herkamp** [comment]
Yes please.  I hope this plugin isn't dead.

**Comment by prog110** [comment]
@clarkedesign @wherkamp Sorry for the delay from my end. I'm not working actively on bootstrap. I'll need to combine both vscode & intellij versions into a single codebase & only then I want to publish a new version of the plugin

As of now, I am quite occupied with some personnel work. Will try to publish new a newer version in couple of weeks.

**Comment by wyatt-herkamp** [comment]
Awesome and thank you. I do want to tell you that bootstrap updated to 4.1 last night.

**Comment by luodaise** [comment]
i cant install it on intellij  ,it alert ""Plugin Bootstrap 4 & Font awesome was not installed: Cannot download 'https://plugins.jetbrains.com/pluginManager/?action=download&id=in.thekalinga.snippet.intellij&build=IU-173.4548.28&uuid=a7042e36-4989-41cf-99d6-eaccc79d9f0a': Read timed out""
and i downloadzip to my pc  install plugin from disk it alert ''Fail to load plugin descriptor from file bootstrap4-intellij-2.1.2.zip''

**Comment by prog110** [comment]
Published v6.0.0 with the required fixes
